spring.application.name=backend

server.port = 8081

#spring.data.mongodb.uri=mongodb+srv://dhatric22:dhatric22@loan.uitmf.mongodb.net/lat-as?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://dhatric22:dhatric22@loan.uitmf.mongodb.net/lat-as?retryWrites=true&w=majority&ssl=true

spring.data.mongodb.database=lat-as

#spring.data.mongodb.uri=mongodb://localhost:27017/db
#spring.data.mongodb.database=db

#spring.data.mongodb.uri=mongodb://localhost:27017/Loan
#spring.data.mongodb.database=Loan



logging.level.org.springframework.data.mongodb.core=DEBUG

spring.redis.host=redis-19810.crce182.ap-south-1-1.ec2.redns.redis-cloud.com
spring.redis.port=19810
spring.redis.password=5YnWMTjGEyIM3EOPemIE1A5OPEV3C0hR
spring.redis.ssl=false

# RabbitMQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

jwt.secret=MySuperSecureSecretKeyThatIsLongEnough12345